#配置数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.89.169:3306/www?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #设置文件上传参数
  servlet:
    multipart:
      max-request-size: 10MB
      enabled: false
  #对于rabbitMQ的支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
  #国际化配置
  messages:
    basename: i18n/messages
  redis:
    host: 192.168.89.169
    port: 6380
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2

#MyBatis中的mapper.xml的配置
mybatis:
  type-aliases-package: com.han.test.springboot_test3.mapper
  mapper-locations: classpath:mapperXml/BacklogMapper.xml

#添加日志级别
debug: true

server:
  port: 8088
  tomcat:
    maxHttpHeaderSize: 66665536


logging:
  level:
    com.han.test.springboot_test3.mapper: DEBUG
    root: INFO
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure: ERROR
      hibernate: ERROR






