#配置数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/www?useSSL=false&allowMultiQueries=true
    username: root
    password: h384175954+
  #设置文件上传参数
  servlet:
    multipart:
      max-request-size: 10MB
      enabled: false
#对于rabbitMQ的支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

#MyBatis中的mapper.xml的配置
mybatis:
  type-aliases-package: com.han.test.springboot_test3.mapper
  mapper-locations: classpath:mapperXml/BacklogMapper.xml

#添加日志级别
debug: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure: ERROR
      hibernate: ERROR



